name: bdsim.micropython

channels:
  - defaults
  - conda-forge

dependencies:
  - micropython = 1.13
  - python = 3.4 # micropython 1.13 only (almost) fully supports 3.4
  # see https://github.com/micropython/micropython/issues/1329
  - pip = 9 # this is the last supported version for py3.4

  - pip:
      - -r file:../../requirements.txt
