name: bdsim.micropython

channels:
  - defaults
  - conda-forge

dependencies:
  - micropython = 1.13
  - python = 3.4 # micropython 1.13 only (almost) fully supports 3.4
  # see https://github.com/micropython/micropython/issues/1329
  - pip = 9 # this is the last supported version for py3.4

  - pip:
      - -r file:../../requirements.txt
      - numpy == 1.16
      - typing_extensions == 3.7.4.3 # unsure how use of this will end up as frozen micropython bytecode
      # will probably need to use a combination of strip-hints and some manual removal of importing from `typing_extensions` and `typing`
      - matplotlib == 2.2.5
      - ansitable == 0.9.5
